[project]
name = 'Blockchain-Based-Legal-Evidence-Management'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.authentication]
path = 'contracts/authentication.clar'
clarity_version = 2
epoch = 2.5

[contracts.retention]
path = 'contracts/retention.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
